# TYPE   DATABASE  USER  ADDRESS      METHOD
local    all       all                trust

# Network connections: SIRF TLS + scram-sha-256 password
hostssl  all       all   0.0.0.0/0    scram-sha-256
hostssl  all       all   ::/0         scram-sha-256

# Non-TLS connection hamesha reject
host     all       all   0.0.0.0/0    reject
host     all       all   ::/0         reject