"""create_initial_financial_schema

Revision ID: 886df85e818f
Revises:
Create Date: 2026-10-09 19:23:29.841897

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "886df85e818f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchanges",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=50), server_default="Asia/Kolkata", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchanges")),
    )
    op.create_index(op.f("ix_exchanges_code"), "exchanges", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "password_expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now() + interval '30 days'"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "market_segments",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("exchange_id", sa.SmallInteger(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["exchange_id"], ["exchanges.id"], name=op.f("fk_market_segments_exchange_id_exchanges"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_segments")),
    )
    op.create_index(op.f("ix_market_segments_code"), "market_segments", ["code"], unique=False)
    op.create_index(op.f("ix_market_segments_exchange_id"), "market_segments", ["exchange_id"], unique=False)
    op.create_table(
        "master_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_master_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_master_keys")),
    )
    op.create_index(op.f("ix_master_keys_id"), "master_keys", ["id"], unique=False)
    op.create_index(op.f("ix_master_keys_user_id"), "master_keys", ["user_id"], unique=False)
    op.create_table(
        "password_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_password_history_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_history")),
    )
    op.create_index(op.f("ix_password_history_id"), "password_history", ["id"], unique=False)
    op.create_index(op.f("ix_password_history_user_id"), "password_history", ["user_id"], unique=False)
    op.create_table(
        "trading_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_number", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trading_accounts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_accounts")),
    )
    op.create_index(op.f("ix_trading_accounts_account_number"), "trading_accounts", ["account_number"], unique=True)
    op.create_index(op.f("ix_trading_accounts_id"), "trading_accounts", ["id"], unique=False)
    op.create_index(op.f("ix_trading_accounts_user_id"), "trading_accounts", ["user_id"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
    )
    op.create_index(op.f("ix_user_sessions_id"), "user_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_user_sessions_token_hash"), "user_sessions", ["token_hash"], unique=False)
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "account_balances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("available_balance", sa.Numeric(precision=20, scale=8), server_default="0.0", nullable=False),
        sa.Column("blocked_balance", sa.Numeric(precision=20, scale=8), server_default="0.0", nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=20, scale=8), server_default="0.0", nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=20, scale=8), server_default="0.0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_account_balances_account_id_trading_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_balances")),
    )
    op.create_index(op.f("ix_account_balances_account_id"), "account_balances", ["account_id"], unique=True)
    op.create_index(op.f("ix_account_balances_id"), "account_balances", ["id"], unique=False)
    op.create_table(
        "fund_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("transaction_type", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("reference_type", sa.String(length=30), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_fund_ledger_account_id_trading_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fund_ledger")),
    )
    op.create_index(op.f("ix_fund_ledger_account_id"), "fund_ledger", ["account_id"], unique=False)
    op.create_index(op.f("ix_fund_ledger_created_at"), "fund_ledger", ["created_at"], unique=False)
    op.create_index(op.f("ix_fund_ledger_id"), "fund_ledger", ["id"], unique=False)
    op.create_index(op.f("ix_fund_ledger_reference_id"), "fund_ledger", ["reference_id"], unique=False)
    op.create_index(op.f("ix_fund_ledger_transaction_type"), "fund_ledger", ["transaction_type"], unique=False)
    op.create_table(
        "instruments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exchange_id", sa.SmallInteger(), nullable=False),
        sa.Column("segment_id", sa.SmallInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("trading_symbol", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("instrument_type", sa.String(length=30), nullable=False),
        sa.Column("isin", sa.String(length=20), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("strike_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("option_type", sa.String(length=10), nullable=True),
        sa.Column("lot_size", sa.Integer(), server_default="1", nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=20, scale=8), server_default="0.05", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["exchange_id"], ["exchanges.id"], name=op.f("fk_instruments_exchange_id_exchanges"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["market_segments.id"],
            name=op.f("fk_instruments_segment_id_market_segments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
    )
    op.create_index(op.f("ix_instruments_exchange_id"), "instruments", ["exchange_id"], unique=False)
    op.create_index(op.f("ix_instruments_expiry_date"), "instruments", ["expiry_date"], unique=False)
    op.create_index(op.f("ix_instruments_id"), "instruments", ["id"], unique=False)
    op.create_index(op.f("ix_instruments_instrument_type"), "instruments", ["instrument_type"], unique=False)
    op.create_index(op.f("ix_instruments_isin"), "instruments", ["isin"], unique=False)
    op.create_index(op.f("ix_instruments_segment_id"), "instruments", ["segment_id"], unique=False)
    op.create_index(op.f("ix_instruments_symbol"), "instruments", ["symbol"], unique=False)
    op.create_index(op.f("ix_instruments_trading_symbol"), "instruments", ["trading_symbol"], unique=False)
    op.create_table(
        "market_candles",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("open_interest", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_market_candles_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instrument_id", "timeframe", "time", name="pk_market_candles"),
    )
    op.create_index(op.f("ix_market_candles_instrument_id"), "market_candles", ["instrument_id"], unique=False)
    op.create_table(
        "market_ticks",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("last_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("last_quantity", sa.BigInteger(), nullable=True),
        sa.Column("bid_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("bid_quantity", sa.BigInteger(), nullable=True),
        sa.Column("ask_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("ask_quantity", sa.BigInteger(), nullable=True),
        sa.Column("volume", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("open_interest", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="FEED", nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_market_ticks_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instrument_id", "time", name="pk_market_ticks"),
    )
    op.create_index(op.f("ix_market_ticks_instrument_id"), "market_ticks", ["instrument_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("trigger_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("product_type", sa.String(length=20), nullable=False),
        sa.Column("validity", sa.String(length=20), server_default="DAY", nullable=False),
        sa.Column("status", sa.String(length=30), server_default="PENDING", nullable=False),
        sa.Column("filled_quantity", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("average_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("placed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_orders_account_id_trading_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"], ["instruments.id"], name=op.f("fk_orders_instrument_id_instruments"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_account_id"), "orders", ["account_id"], unique=False)
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_index(op.f("ix_orders_instrument_id"), "orders", ["instrument_id"], unique=False)
    op.create_index(op.f("ix_orders_placed_at"), "orders", ["placed_at"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("average_price", sa.Numeric(precision=20, scale=8), server_default="0.0", nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=20, scale=8), server_default="0.0", nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=20, scale=8), server_default="0.0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_positions_account_id_trading_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_positions_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint("account_id", "instrument_id", name="uq_positions_account_instrument"),
    )
    op.create_index(op.f("ix_positions_account_id"), "positions", ["account_id"], unique=False)
    op.create_index(op.f("ix_positions_id"), "positions", ["id"], unique=False)
    op.create_index(op.f("ix_positions_instrument_id"), "positions", ["instrument_id"], unique=False)
    op.create_table(
        "executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("charges", sa.Numeric(precision=20, scale=8), server_default="0.0", nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_executions_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_executions_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
    )
    op.create_index(op.f("ix_executions_executed_at"), "executions", ["executed_at"], unique=False)
    op.create_index(op.f("ix_executions_id"), "executions", ["id"], unique=False)
    op.create_index(op.f("ix_executions_instrument_id"), "executions", ["instrument_id"], unique=False)
    op.create_index(op.f("ix_executions_order_id"), "executions", ["order_id"], unique=False)
    op.create_table(
        "order_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_events_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_events")),
    )
    op.create_index(op.f("ix_order_events_created_at"), "order_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_order_events_event_type"), "order_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_order_events_id"), "order_events", ["id"], unique=False)
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)
    op.create_table(
        "position_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("quantity_change", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=20, scale=8), server_default="0.0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name=op.f("fk_position_events_execution_id_executions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_position_events_position_id_positions"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_events")),
    )
    op.create_index(op.f("ix_position_events_created_at"), "position_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_position_events_execution_id"), "position_events", ["execution_id"], unique=False)
    op.create_index(op.f("ix_position_events_id"), "position_events", ["id"], unique=False)
    op.create_index(op.f("ix_position_events_position_id"), "position_events", ["position_id"], unique=False)

    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")
    op.execute(
        "SELECT create_hypertable('market_ticks', 'time', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);"
    )
    op.execute(
        "SELECT create_hypertable('market_candles', 'time', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE);"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_position_events_position_id"), table_name="position_events")
    op.drop_index(op.f("ix_position_events_id"), table_name="position_events")
    op.drop_index(op.f("ix_position_events_execution_id"), table_name="position_events")
    op.drop_index(op.f("ix_position_events_created_at"), table_name="position_events")
    op.drop_table("position_events")
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_index(op.f("ix_order_events_id"), table_name="order_events")
    op.drop_index(op.f("ix_order_events_event_type"), table_name="order_events")
    op.drop_index(op.f("ix_order_events_created_at"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_executions_order_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_instrument_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_executed_at"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(op.f("ix_positions_instrument_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_account_id"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_placed_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_instrument_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_account_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_market_ticks_instrument_id"), table_name="market_ticks")
    op.drop_table("market_ticks")
    op.drop_index(op.f("ix_market_candles_instrument_id"), table_name="market_candles")
    op.drop_table("market_candles")
    op.drop_index(op.f("ix_instruments_trading_symbol"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_symbol"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_segment_id"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_isin"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_instrument_type"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_id"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_expiry_date"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_exchange_id"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_fund_ledger_transaction_type"), table_name="fund_ledger")
    op.drop_index(op.f("ix_fund_ledger_reference_id"), table_name="fund_ledger")
    op.drop_index(op.f("ix_fund_ledger_id"), table_name="fund_ledger")
    op.drop_index(op.f("ix_fund_ledger_created_at"), table_name="fund_ledger")
    op.drop_index(op.f("ix_fund_ledger_account_id"), table_name="fund_ledger")
    op.drop_table("fund_ledger")
    op.drop_index(op.f("ix_account_balances_id"), table_name="account_balances")
    op.drop_index(op.f("ix_account_balances_account_id"), table_name="account_balances")
    op.drop_table("account_balances")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_token_hash"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_trading_accounts_user_id"), table_name="trading_accounts")
    op.drop_index(op.f("ix_trading_accounts_id"), table_name="trading_accounts")
    op.drop_index(op.f("ix_trading_accounts_account_number"), table_name="trading_accounts")
    op.drop_table("trading_accounts")
    op.drop_index(op.f("ix_password_history_user_id"), table_name="password_history")
    op.drop_index(op.f("ix_password_history_id"), table_name="password_history")
    op.drop_table("password_history")
    op.drop_index(op.f("ix_master_keys_user_id"), table_name="master_keys")
    op.drop_index(op.f("ix_master_keys_id"), table_name="master_keys")
    op.drop_table("master_keys")
    op.drop_index(op.f("ix_market_segments_exchange_id"), table_name="market_segments")
    op.drop_index(op.f("ix_market_segments_code"), table_name="market_segments")
    op.drop_table("market_segments")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_exchanges_code"), table_name="exchanges")
    op.drop_table("exchanges")
    # ### end Alembic commands ###
